services:
  medplum-postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: medplum
      POSTGRES_USER: medplum
      POSTGRES_PASSWORD: medplum
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medplum"]
      interval: 5s
      timeout: 5s
      retries: 10

  medplum-redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  medplum-server:
    image: medplum/medplum-server:latest
    ports:
      - "8103:8103"
    volumes:
      - ./medplum.config.json:/usr/src/medplum/medplum.config.json
    depends_on:
      medplum-postgres:
        condition: service_healthy
      medplum-redis:
        condition: service_healthy

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns,s3,sqs,events
      DEFAULT_REGION: us-east-1
